### PR TITLE
Fix some Py3 incompatibilities

### PR DESCRIPTION
**Pull request by Sillern**
This change is generated from `futurize --stage1`

Replace `sys.maxint` with `sys.maxsize`
Replace `,e ` with `as e` in exception handler

### CODE REVIEW

**Comment by kanzure** [comment]
i have no particular interest in old python stuff

**Comment by olsonse** [comment]
If you could create a fork on github and then push your changes to your fork, it would make it easier to check it out and comment.  I am actually moving most of my projects slowly to either dual 2.7/3.x support or just 3.x.  Hence, I will need to soon look at options to move the ctypesgen to generate code for 3.x.  From a very cursory glance it didn't look like it was too challenging, but it might be helpful to start where you have already changed things...

**Comment by tholom** [comment]
OK, that should be visible as tholom/ctypesgen (py3 version only...I guess I should have indicated that with a name change or something).

**Comment by olsonse** [comment]
Spent a bit of time with needing to update to Python3 as well finally.  My repository now includes a version that passes unit tests for Python3 and also for at least Python2.7(.15).  If you generate code for Python3(.6), the code does appear to also work for at least Python2.7(.15).

**Comment by scorp08** [comment]
Hello 
@tholom , @olsonse  for python3 , is it can be used? If you are still on the progress, I can give a hand

**Comment by olsonse** [comment]
I updated this a while ago and have been using this for py3 for some time.
It should work...

**Comment by scorp08** [comment]
@olsonse ,thnks. I was trying to install https://github.com/kanzure/python-brlcad repo which depends on ctypesgen but it works for py2. I changed some part of brlcad to py3 and installed your repo instead of "davidjamesca/ctypesgen"  . when I tried to install brlcad , returned with errors that looking for "ctypesgencore". guessing you had change to ctypesgen. What kind of changes do I need  in python-brlcad to install it. It would be very helpful for me if you have any info about python-brlcad repo

**Comment by loonydev** [comment]
Also create pull request to this fork with https://github.com/davidjamesca/ctypesgen/issues/60 changes. If @Sillern accept my pull this fork also fix enum problem. Thx @kpoman.

**Comment by Alan-R** [comment]
@Sillern I suspect that this branch is no longer useful. Please check the current tip of master and see if it meets your needs.

**Comment by olsonse** [comment]
These changes are all reflected in the various changes that are now already made in the current master branch.

**Pull request closed without merging**
