### PR TITLE
Merge in various changes from kanzure and olsonse

### PR DESCRIPTION
**Pull request by olsonse**
@kanzure and @olsonse have made a few changes and fixed a few items over the past years.  These items had not been merged back into the SVN that was on code.google.com.  With the upstream of this project moving to github.com, it is desirable that the two lines get merged back.  We would appreciate if upstream would accept changes that are applied to a prior svn-to-git base, to preserve history.

Short summary of merged changes:
- adds a .gitignore file
- make "main" of ctypesgen.py be a callable function called 'main'
- fix macro sub-calls; add lots of unit tests for these
- append paths for finding libraries and ensure that they get converted to absolute paths (allows relative paths to be used)
- ensure that only valid items can get marked as anonymous (following ctypes documentation that only structs and unions can be marked as anonymous)

### CODE REVIEW

**Comment by ZenithDK** [comment]
The fixes here seem pretty large, important, and by now - urgent.
Is it recommended to use pip to install the version from olsonse (https://github.com/olsonse/ctypesgen) directly instead?

**Comment by olsonse** [comment]
I have not tested installing this with pip from github--I rarely use pip.  That being said, I do agree that the changes included on my master branch are somewhat critical and urgent.  I do not mind keeping things updated for the foreseeable future, until something else comes along that is significantly better.

**Comment by Alan-R** [comment]
Hi,

Apparently, I hadn't noticed your changes - and went and probably fixed some of the same things you fixed, converted it to run under and generate python3-compliant code, and made all the tests run under tox, and reformatted everything to be uniformly formatted using the black formatter.

Is there any chance you can look at my branch, and see how hard it would be to put your changes on top of mine?  https://github.com/Alan-R/ctypesgen

**Comment by Alan-R** [comment]
I'm going to pull this one in - it definitely has fixes my branch doesn't have. Then I'll reformat to black, and see if any of my changes are needed any longer. Mine just concentrated on python 3 compliance and fixing some bugs that kept it from working with somewhat more modern C.

**Comment by Alan-R** [comment]
@olsonse, @kanzure, @olivierberten, @ZenithDK @davidjamesca:

This has been merged in and two other changes made on top of this:
1) Code was completely reformatted with 'black'. This will be a requirement going forward.
2) tests were moved to be a subdirectory in the package
3) I added tox testing to the code - and fixed an options problem which I presume was py26 incompatibility.

I haven't yet tested this with the Assimilation code (my project), but it passes all the tests in both py26 and py27. Please check and ensure that you're happy with it.

**Pull request merged**
